In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv("/Users/raghavagovil/Desktop/FIFA-Data-Analysis/FifaTrainNew.csv")
test = pd.read_csv("/Users/raghavagovil/Desktop/FIFA-Data-Analysis/FifaTestNoYvalues.csv")

In [3]:
train.head()

,Ob,WageNew,Age,Nationality,Overall,Potential,Club,Special,Preferred Foot,International Reputation,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,1,26735,25,Austria,77,80,FC Augsburg,1971,Left,2.0,...,64.0,65.0,77.0,78.0,77.0,14.0,14.0,9.0,13.0,10.0
1,2,3709,22,Saudi Arabia,58,67,Al Wehda,1510,Right,1.0,...,48.0,43.0,52.0,54.0,56.0,7.0,7.0,12.0,11.0,14.0
2,3,4720,29,Austria,66,66,LASK Linz,1356,Right,1.0,...,42.0,63.0,65.0,64.0,66.0,9.0,11.0,8.0,6.0,12.0
3,4,31062,24,Sweden,71,73,Watford,1824,Left,1.0,...,44.0,62.0,36.0,49.0,48.0,7.0,11.0,10.0,16.0,7.0
4,5,43797,26,Colombia,80,84,Valencia CF,1847,Right,2.0,...,46.0,73.0,77.0,80.0,82.0,14.0,13.0,8.0,11.0,14.0

In [4]:
train.describe()

,Ob,WageNew,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Crossing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12745.000000,12745.000000,12745.000000,12745.000000,12745.000000,12745.000000,12707.000000,12707.000000,12707.000000,12707.000000,...,12707.000000,12707.000000,12707.000000,12707.000000,12707.000000,12707.000000,12707.000000,12707.000000,12707.000000,12707.000000
mean,6373.000000,11432.671479,25.048647,66.139506,71.293841,1594.873127,1.108838,2.940033,2.358385,49.592193,...,48.368773,58.461006,47.120563,47.624852,45.617298,16.684347,16.439207,16.274888,16.444558,16.769891
std,3679.308925,24697.500001,4.660086,6.923195,6.165601,272.439485,0.382861,0.659497,0.755791,18.346317,...,15.730019,11.461340,19.829982,21.607900,21.235074,17.742196,16.966393,16.537873,17.098058,18.026685
min,1.000000,6.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,5.000000,...,5.000000,3.000000,3.000000,5.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3187.000000,2004.000000,21.000000,62.000000,67.000000,1452.000000,1.000000,3.000000,2.000000,38.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6373.000000,3926.000000,25.000000,66.000000,71.000000,1632.000000,1.000000,3.000000,2.000000,54.000000,...,49.000000,59.000000,52.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9559.000000,10528.000000,28.000000,71.000000,75.000000,1785.000000,1.000000,3.000000,3.000000,64.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,12745.000000,650305.000000,44.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,92.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12745 entries, 0 to 12744
Data columns (total 81 columns):
Ob                          12745 non-null int64
WageNew                     12745 non-null int64
Age                         12745 non-null int64
Nationality                 12745 non-null object
Overall                     12745 non-null int64
Potential                   12745 non-null int64
Club                        12577 non-null object
Special                     12745 non-null int64
Preferred Foot              12707 non-null object
International Reputation    12707 non-null float64
Weak Foot                   12707 non-null float64
Skill Moves                 12707 non-null float64
Work Rate                   12707 non-null object
Body Type                   12707 non-null object
Real Face                   12707 non-null object
Position                    12698 non-null object
Joined                      11640 non-null object
Loaned From                 899 non-null object
Contract Valid Until        12539 non-null object
Height                      12707 non-null object
Weight                      12707 non-null object
LS                          11268 non-null object
ST                          11268 non-null object
RS                          11268 non-null object
LW                          11268 non-null object
LF                          11268 non-null object
CF                          11268 non-null object
RF                          11268 non-null object
RW                          11268 non-null object
LAM                         11268 non-null object
CAM                         11268 non-null object
RAM                         11268 non-null object
LM                          11268 non-null object
LCM                         11268 non-null object
CM                          11268 non-null object
RCM                         11268 non-null object
RM                          11268 non-null object
LWB                         11268 non-null object
LDM                         11268 non-null object
CDM                         11268 non-null object
RDM                         11268 non-null object
RWB                         11268 non-null object
LB                          11268 non-null object
LCB                         11268 non-null object
CB                          11268 non-null object
RCB                         11268 non-null object
RB                          11268 non-null object
Crossing                    12707 non-null float64
Finishing                   12707 non-null float64
HeadingAccuracy             12707 non-null float64
ShortPassing                12707 non-null float64
Volleys                     12707 non-null float64
Dribbling                   12707 non-null float64
Curve                       12707 non-null float64
FKAccuracy                  12707 non-null float64
LongPassing                 12707 non-null float64
BallControl                 12707 non-null float64
Acceleration                12707 non-null float64
SprintSpeed                 12707 non-null float64
Agility                     12707 non-null float64
Reactions                   12707 non-null float64
Balance                     12707 non-null float64
ShotPower                   12707 non-null float64
Jumping                     12707 non-null float64
Stamina                     12707 non-null float64
Strength                    12707 non-null float64
LongShots                   12707 non-null float64
Aggression                  12707 non-null float64
Interceptions               12707 non-null float64
Positioning                 12707 non-null float64
Vision                      12707 non-null float64
Penalties                   12707 non-null float64
Composure                   12707 non-null float64
Marking                     12707 non-null float64
StandingTackle              12707 non-null float64
SlidingTackle               12707 non-null float64
GKDiving                    12707 non-null float64
GKHandling                  12707 non-null float64
GKKicking                   12707 non-null float64
GKPositioning               12707 non-null float64
GKReflexes                  12707 non-null float64
dtypes: float64(37), int64(6), object(38)
memory usage: 7.9+ MB